### ISSUE TITLE
Boundary terms in MA

### ISSUE THREAD

**Issue by stephankramer** [pyroteus/movement#62]
Looking at #61 I'm getting a little confused about the bcs being applied in the MA

[Here in the relaxation method](https://github.com/pyroteus/movement/blob/25cf05834c6aeee17e71b7345c49178024cc9341/movement/monge_ampere.py#L336)

and

[here in the Newton method](https://github.com/pyroteus/movement/blob/25cf05834c6aeee17e71b7345c49178024cc9341/movement/monge_ampere.py#L464)

Naively I would say, we start from:

```
sigma_ij = d_i d_j phi     (d_i is short for \nabla_i)
weak form:   (tau_ij sigma_ij - tau_ij d_i d_j phi) dx
ibp:    tau_ij sigma_ij dx - d_i (tau_ij d_j phi) dx + (d_i tau_ij) (d_j phi) dx = 
        tau_ij sigma_ij dx - n_i tau_ij d_j phi ds + (d_i tau_ij) (d_j phi) dx
```
           
So the boundary term is ```- n_i tau_ij d_j phi ds```. If we want to weakly impose
`n_k d_k phi = 0`, then in 2D we can say `I_ij = n_i n_j + t_i t_j` where `t` is the tangent vector, so
```
n_i tau_ij d_j phi ds = n_i tau_ij n_j n_k d_k phi + n_i tau_ij t_j t_k d_k phi
```
where the first term is replaced by 0, but then with `n=[n0,n1]` and thus `t=[-n1,n0]`, I get
```
(-n0 tau_00 n1 + n0 tau_01 n0 - n1 tau_10 n1 + n1 tau_11 n0) (-n1 d0 phi + n0 d1 phi)
```
which I can't work out any further. For the Cartesian aligned case, where `n0 n1 =0` and `n0^2=n1^2=1`, however it does give the same thing:
```
n0^3 tau_01 d1 phi + n1^3 tau_10 d0 phi = n0 tau_01 d1 phi + n1 tau_10 d0 phi
```

@jwallwork23 - do you perhaps have a reference where the bcs are discussed? - I can't find it in McRae.

**Comment by jwallwork23** [comment]
Ah sorry about this. Both undocumented and potentially wrong.

It may just be an incorrect application of IBP that happens to work out in the Cartesian axis-aligned case. I will almost certainly have been trying to make use of the assumption $\mathbf{u}\cdot\mathbf{n}=0$ (tangential boundary movement only), i.e., $\nabla\phi\cdot\mathbf{n}=0$. I followed through your derivations above and tried making use of this. It doesn't get us much further, although it does allow us to drop the first term on the RHS of
$$n_i \tau_{ij} \partial_j \phi = n_i \tau_{ij} n_j n_k\partial_j \phi + n_i \tau_{ij} t_j t_k\partial_j \phi$$

There aren't any other BCs being applied to the equidistributors, so we do need to impose something. Perhaps it would be sufficient to use something like this expression, to bake in the assumption that there is no tangential movement?

**Comment by jwallwork23** [comment]
Oh! I just remembered the demo this code will definitely have borrowed from: https://www.firedrakeproject.org/demos/ma-demo.py.html. The same BCs are used as I mention here and the formulation is the same.

**Comment by stephankramer** [comment]
Thanks, I checked with @colinjcotter and he confirms that he indeed assumes a Cartesian (original) mesh.

Yeah so just as you say indeed - also writing with a single tangential vector of course only works in 2D. So the more compact way to write this is to decompose:

$$
  \nabla\phi = (n\cdot\nabla\phi) n + \left[\nabla\phi - (n\cdot\nabla\phi) n\right]
$$

where we drop the first part to weakly impose $n\cdot\nabla\phi=0$ and then we get:

$$
\int_\Gamma n\cdot\tau\cdot\nabla\phi ds \to
\int_\Gamma n\cdot\tau\cdot\left[\nabla\phi - (n\cdot\nabla\phi) n\right] ds
$$

This seems to work well now - after I realized that because we are using `ufl.div(tau)` (as opposed to `nabla_div`) which contracts the derivative with the second index of `tau`, the normal in the boundary term should also contract with that index!
